version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

snapshot:
  name_template: "{{ .Tag }}-next"

signs:
  - artifacts: checksum
    args: ["--armor", "--detach-sign"]

release:
  draft: false
  prerelease: auto

builds:
  - main: ./cmd/trazr-gen
    binary: trazr-gen
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

brews:
  - name: trazr-gen
    repository:
      owner: 'medxops'
      name: 'homebrew-tap'
    homepage: https://github.com/medxops/trazr-gen
    description: "A tool to generate synthetic OpenTelemetry logs, metrics and traces telemetry data."
    install: |
      bin.install "trazr-gen"
    test: |
      system "#{bin}/trazr-gen -v"
