name: Publish (docker)

on:
  release:
    types:
      - published

env:
  REGISTRY_IMAGE: ghcr.io/krzko/otelgen

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: version
        run: echo "VERSION=$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          docker buildx build \
            --build-arg=BUILD_VERSION=${{ env.VERSION }} \
            --build-arg=BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg=COMMIT_ID=${{ github.sha }} \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }} \
            -t ${{ env.REGISTRY_IMAGE }}:${{ github.sha }} \
            -t ${{ env.REGISTRY_IMAGE }}:latest \
            --push \
            .
